config/routes.rb
Day2PrayerWall::Application.routes.draw do

  resources :posts do
    get '/pray', to: :pray
    resources :comments, only: [:create]
  end

  resources :users, only: [:new, :create]

  resources :user_sessions, only: [:new, :create, :destroy]
  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

  root to: 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :prayers
  has_many :supporters, through: :prayers, source: :user
  validates_presence_of :body

  accepts_nested_attributes_for :comments
end

app/models/prayer.rb
class Prayer < ActiveRecord::Base
  validates_uniqueness_of :user_id, :scope => :post_id

  belongs_to :user
  belongs_to :post
end

app/models/prayers.rb
class Prayer < ActiveRecord::Base
  validates_uniqueness_of :user_id, scope: :post_id

  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password

  has_many :posts
  has_many :prayers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.last(10)
  end

  def create
    post = Post.new(post_params)
    if post.save
      redirect_to post_path(post)
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def destroy
  end

  def update
    @post = Post.find(params[:id])
    @post.comments.build(comment_params)
    @post.save
    redirect_to post_path(@post)
  end

  def pray
    Prayer.find_or_create_by(user_id: current_user.id, post_id: params[:post_id])
    render status: 200
    redirect_to post_path(params[:post_id])
  end

  private

    def post_params
      params.require(:post).permit(:body, :comment_params)
    end

    def comment_params
      params.require(:comment).permit!
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_to(posts_path, message: 'Logged in!')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:posts, message: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :zero_authors_or_authenticated, only: [:new, :create]

  # def zero_authors_or_authenticated
  #   unless User.count == 0 || current_user
  #     redirect_to root_path
  #     return false
  #   end
  # end

  def index

  end

  def new
    @user = User.new
    render partial: 'form'
  end

  def create
    user = User.new(username: user_params[:email], password: user_params[:password])
    if user.save
      login(user_params[:email], user_params[:password])
      redirect_to posts_path
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day2PrayerWall</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <h6>
      <% if logged_in? %>
        <%= "Logged in #{current_user.email}" %>
        <%= link_to '[logout]', logout_path %>
      <% else %>
        Currently logged out
        <%= link_to '[login]', login_path %>
      <% end %>
    </h6>
  </div>

  <%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="prayer">
      by <em>Anonymous at <%= post.created_at.ctime %></em>
      <p>
        <%= link_to post.body, post %>
      </p>
    </div>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.text_area :body %>
  <%= f.label :body %>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h4>
  Posted By: <em>Anonymous at <%= @post.created_at.ctime %></em>
  <%= @post.prayers.count %> have prayed for this.
  <br>
  <% if Prayer.all.where(:user_id => current_user.id, :post_id => @post.id).empty? %>
    <%= link_to "Click to show that you prayed for this!", post_pray_path(@post) %>
  <% else %>
    <%= "you prayed for this" %>
  <% end %>

</h4>
<p><%= @post.body %></p>
<br>
<% if @post.comments %>
  Comments:
  <br><br>
  <% @post.comments.each_with_index do |comment, i| %>
    <%= render partial: 'shared/comment_show', :locals => { :comment => comment, :i => (i + 1) } %>
  <% end %>
  <br>
<% end %>
<%= render partial: 'shared/comment_form' %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/shared/_comment_form.html.erb
<%= form_for @post do |f| %>
  <%= fields_for @comment do |c| %>
    <%= c.label :body, 'comment:' %>
    <br>
    <%= c.text_area :body %>
    <br>
  <% end %>
  <%= f.submit 'submit' %>
<% end %>

app/views/shared/_comment_show.html.erb
<div class='comment'>
  <%= i.to_s + '.  ' + comment.body %>
</div>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_for user_sessions_path, url: '/user_sessions' do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', posts_path %> | <%= link_to 'New User', new_user_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %><br />
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>